In [31]:
#Question 01
def greedyAlgorithm(graph, start, goal, hn,  open_q, close_q=[]):
    print(start, end='-->')
    close_q.append(start)
    open_q.remove(start)
    if start == goal:
        return 0
    mini = float('inf')
    node = ''
    for i in range(len(graph[start])):
        open_q.append(graph[start][i])
        
    for i in range(len(open_q)):
        if mini > hn[open_q[i]]:
            mini, node = hn[open_q[i]], open_q[i]
    return mini + greedyAlgorithm(graph, node, goal, hn,  open_q, close_q)
graph = { 'S': ['A', 'B'], 'A': ['C', 'D'], 'B': ['E', 'F'], 'C': [], 'D': [], 'E': ['H'],
          'F': ['I','G'], 'G': [], 'H': [], 'I':[] }
hn = {'A': 12, 'B': 4, 'C':7, 'D':3,'E': 8,'F': 2,'G': 4,'H': 4,'I': 9,'S': 13,'G':0}
gn = {'S-A': 3, 'S-B': 2, 'A-C': 4,'A-D': 1, 'B-E':3, 'B-F':1,'E-H':5,'F-I':2, 'F-G':3}
result = greedyAlgorithm(graph, 'S', 'H', hn, ['S'])

S-->B-->F-->G-->E-->H-->

In [32]:
#Question 02
def astar(graph, start, goal, gn, hn, open_q, close_q=[], cost=0):
    print(start, end='-->')
    close_q.append(start)
    open_q.remove(start)
    if start == goal:
        return cost

    mini = float('inf')
    node = ''
    temp = cost
    for i in range(len(graph[start])):
        open_q.append(graph[start][i])
        
    for i in range(len(open_q)):
        if str(start + '-' + open_q[i]) in gn.keys():
            fn = cost + (gn[start + '-' + open_q[i]] + hn[open_q[i]])
            if mini > fn:
                mini, node = fn, open_q[i]
                temp = gn[start + '-' + open_q[i]]
    return astar(graph, node, goal, gn, hn, open_q, close_q, cost+temp)
graph = { 'S': ['A', 'G'], 'A': ['B', 'C'], 'B': ['D'], 'C': ['D','G'], 'D': ['G'], 'G': [] }
hn = {'A': 3, 'B': 4, 'C':2, 'D':6, 'S': 5,'G':0}
gn = {'S-A': 1, 'S-G': 10, 'A-B': 2,'A-C': 1, 'B-D':5, 'C-D':3,'C-G':4,'D-G':6}
print(astar(graph, 'S', 'G', gn, hn, ['S']))

S-->A-->C-->G-->6


In [33]:
#Question 03 (a)
import numpy as np
def MazeGreedyAlgorithm(maze, start, goal, open_q, close_q=[]):
    print(start, end='-->')
    close_q.append(start)
    open_q.remove(start)
    if maze[start[0]][start[1]] == goal:
        return 0
    mini = float('inf')
    i, j = start
    r, c = maze.shape
    node = (-1, -1)
    
    if j+1 < c and maze[i][j+1] != '-1' and not (i, j+1) in close_q and not (i, j+1) in open_q:
        open_q.append((i, j+1))
        
    if i+1 < r and maze[i+1][j] != '-1' and not (i+1, j) in close_q and not (i+1, j) in open_q:
        open_q.append((i+1, j))
        
    if j-1 >= 0 and maze[i][j-1] != '-1' and not (i, j-1) in close_q and not (i, j-1) in open_q:
        open_q.append((i, j-1))
        
    if i-1 >= 0 and maze[i-1][j] != '-1' and not (i-1, j) in close_q and not (i-1, j) in open_q:
        open_q.append((i-1, j))
    
    for p,q in open_q:
        if maze[p][q] == goal or mini > float(maze[p][q]):
            mini, node = 0 if maze[p][q] == goal else float(maze[p][q]), (p,q)
                                 
    return mini + MazeGreedyAlgorithm(maze, node, goal, open_q, close_q)
                                 
def find(node, inmaze):
    for row in range(len(inmaze)):
        for col in range(len(inmaze[row])):
            if inmaze[row][col] == node:
                return (row, col)
            
maze = np.array([[ -1, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1, 'G'],
                 [ -1, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1 ],
                 [ -1, 12, -1, 10,  9,  8,  7,  6,  5,  4, -1,  2 ],
                 [ -1, 13, -1, 11, -1, -1, -1, -1, -1,  5, -1,  3 ],
                 [ -1, 14, 13, 12, -1, 10,  9,  8,  7,  6, -1,  4 ],
                 [ -1, -1, -1, 13, -1, 11, -1, -1, -1, -1, -1,  5 ],
                 ['A', 16, 15, 14, -1, 12, 11, 10,  9,  8,  7,  6 ] ])
start = find('A', maze)
result = MazeGreedyAlgorithm(maze, start, 'G', [start])

(6, 0)-->(6, 1)-->(6, 2)-->(6, 3)-->(5, 3)-->(4, 3)-->(3, 3)-->(2, 3)-->(2, 4)-->(2, 5)-->(2, 6)-->(2, 7)-->(2, 8)-->(2, 9)-->(3, 9)-->(4, 9)-->(4, 8)-->(4, 7)-->(4, 6)-->(4, 5)-->(5, 5)-->(6, 5)-->(6, 6)-->(6, 7)-->(6, 8)-->(6, 9)-->(6, 10)-->(6, 11)-->(5, 11)-->(4, 11)-->(3, 11)-->(2, 11)-->(1, 11)-->(0, 11)-->

In [34]:
#Question 03 (b)
import numpy as np
def MazeAStar(maze, start, goal, open_q, gn, close_q=[], cost=0):
    print(start, end='-->')
    close_q.append(start)
    open_q.remove(start)
    if maze[start[0]][start[1]] == goal:
        return 0
    mini = float('inf')
    i, j = start
    r, c = maze.shape
    node = (-1, -1)
    k = gn[start]
    temp = cost
    
    if j+1 < c and maze[i][j+1] != '-1' and not (i, j+1) in close_q and not (i, j+1) in open_q:
        open_q.append((i, j+1))
        gn[(i, j+1)] = k+1
        
    if i+1 < r and maze[i+1][j] != '-1' and not (i+1, j) in close_q and not (i+1, j) in open_q:
        open_q.append((i+1, j))
        gn[(i+1, j)] = k+1
        
    if j-1 >= 0 and maze[i][j-1] != '-1' and not (i, j-1) in close_q and not (i, j-1) in open_q:
        open_q.append((i, j-1))
        gn[(i, j-1)] = k+1
        
    if i-1 >= 0 and maze[i-1][j] != '-1' and not (i-1, j) in close_q and not (i-1, j) in open_q:
        open_q.append((i-1, j))
        gn[(i-1, j)] = k+1
    
    for p,q in open_q:
        if maze[p][q] == goal:
            mini, node = k, (p, q)
            break
        elif mini > float(maze[p][q]) + gn[(p, q)]:
            mini, node = float(maze[p][q]) + gn[(p, q)], (p, q)
                                 
    return mini + MazeAStar(maze, node, goal, open_q, gn, close_q, cost+1)
                                 
def find(node, inmaze):
    for row in range(len(inmaze)):
        for col in range(len(inmaze[row])):
            if inmaze[row][col] == node:
                return (row, col)
            
maze = np.array([[ -1, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1, 'G'],
                 [ -1, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1 ],
                 [ -1, 12, -1, 10,  9,  8,  7,  6,  5,  4, -1,  2 ],
                 [ -1, 13, -1, 11, -1, -1, -1, -1, -1,  5, -1,  3 ],
                 [ -1, 14, 13, 12, -1, 10,  9,  8,  7,  6, -1,  4 ],
                 [ -1, -1, -1, 13, -1, 11, -1, -1, -1, -1, -1,  5 ],
                 ['A', 16, 15, 14, -1, 12, 11, 10,  9,  8,  7,  6 ] ])
start = find('A', maze)
result = MazeAStar(maze, start, 'G', [start], {start: 17})

(6, 0)-->(6, 1)-->(6, 2)-->(6, 3)-->(5, 3)-->(4, 3)-->(3, 3)-->(2, 3)-->(2, 4)-->(2, 5)-->(2, 6)-->(2, 7)-->(2, 8)-->(2, 9)-->(4, 2)-->(3, 9)-->(4, 1)-->(4, 9)-->(3, 1)-->(2, 1)-->(1, 1)-->(0, 1)-->(0, 2)-->(0, 3)-->(0, 4)-->(0, 5)-->(0, 6)-->(0, 7)-->(0, 8)-->(0, 9)-->(0, 10)-->(0, 11)-->

In [35]:
#Question 04
import copy as cp
import numpy as np
def find(node, inmaze):
    for row in range(len(inmaze)):
        for col in range(len(inmaze[row])):
            if inmaze[row][col] == node:
                return (row, col)
                
def ChangeState(state, dash, move):
    xtemp = cp.deepcopy(state)
    i, j = dash
    x, y = move
    xtemp[i][j], xtemp[x][y] = xtemp[x][y], xtemp[i][j]
    return xtemp

def h(state, goal):
    h = 1
    for i in range(len(state)):
        for j in range(len(state[i])):
            if state[i][j] != goal[i][j]:
                h+=1
    return h

def arraytostring(state):
    ss = ''
    for row in state:
        for num in row:
            ss += str(num)
            
    return ss
                       

def sovlePuzzleAstar(puzzle, goal, dash, gn, open_q, close_q=[]):
    print(np.array(puzzle))
    
    if np.array_equal(puzzle, goal):
        return 0
    
    close_q.append(cp.deepcopy(puzzle))
    open_q.remove(cp.deepcopy(puzzle))
    
    
    
    mini = float('inf')
    i, j = dash
    r, c = (3, 3)
    node = []
    k = gn[arraytostring(cp.deepcopy(puzzle))]
    
    
    if j+1 < c:
        dummy = cp.deepcopy((ChangeState(cp.deepcopy(puzzle), dash, (i, j+1))))
        if not dummy in open_q and not dummy in close_q:
            open_q.append(cp.deepcopy(dummy))
            gn[arraytostring(cp.deepcopy(dummy))] = k+1
        
    if i+1 < r:
        dummy = cp.deepcopy(ChangeState(cp.deepcopy(puzzle), dash, (i+1, j)))
        if not dummy in open_q and not dummy in close_q:
            open_q.append(cp.deepcopy(dummy))
            gn[arraytostring(cp.deepcopy(dummy))] = k+1
        
    if j-1 >= 0:
        dummy = cp.deepcopy(ChangeState(cp.deepcopy(puzzle), dash, (i, j-1)))
        if not dummy in open_q and not dummy in close_q:
            open_q.append(cp.deepcopy(dummy))
            gn[arraytostring(cp.deepcopy(dummy))] = k+1
        
    if i-1 >= 0:
        dummy = cp.deepcopy(ChangeState(cp.deepcopy(puzzle), dash, (i-1, j)))
        if not dummy in open_q and not dummy in close_q:
            open_q.append(cp.deepcopy(dummy))
            gn[arraytostring(cp.deepcopy(dummy))] = k+1
    for game in open_q:
        fn = h(cp.deepcopy(game), goal) + gn[arraytostring(cp.deepcopy(game))]
        if mini > fn:
            mini, node = fn, cp.deepcopy(game)
            
    return mini + sovlePuzzleAstar(node, goal, find(0, node), gn, open_q, close_q)
    
initial = [
    [1, 2, 3],
    [0, 4, 6],
    [7, 5, 8]
]
goal = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
]
sovlePuzzleAstar(initial, goal, find(0, initial), {arraytostring(initial): 0}, [initial])

[[1 2 3]
 [0 4 6]
 [7 5 8]]
[[1 2 3]
 [4 0 6]
 [7 5 8]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


14